name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    # Global environment variables for Gradle
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g"

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Gradle with caching enabled
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Ensure gradlew script is executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run full build & checks (compilation, tests, lint, etc.)
      - name: Build with Gradle
        run: ./gradlew check --no-configuration-cache